[[main]]
  name = "Home"
  pageRef = "/"
  weight = 1

[[main]] 
  name = "Blog"
  pageRef = "posts"
  weight = 10
[[main]] 
  name = "projects"
  pageRef = "projects"
  weight = 20

[[main]]
    identifier = "github"
    pre = "github"
    url="https://github.com/isaaclins"
    weight= 100
[[main]]
    identifier = "linkedin"
    pre = "linkedin"
    url="https://github.com/isaaclins"
    weight= 200
 [[footer]]
   name = "Contact me"
   url = "mailto://isaac.lins07@gmail.com"
