[[main]]
  name = "Home"
  pageRef = "/"
  weight = 1

[[main]] 
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[main]] 
  name = "Projects"
  pageRef = "projects"
  weight = 20

[[main]]
    identifier = "github"
    pre = "github"
    url="https://github.com/isaaclins"
    weight= 100
[[main]]
    identifier = "linkedin"
    pre = "linkedin"
    url="https://www.linkedin.com/in/isaac-lins-094612247/"
    weight= 200
[[main]]
    name ="open Calculator"
    identifier = "wand-magic-sparkles"
    pre = "wand-magic-sparkles"
    url="Calculator:///"
    weight= 300

 [[footer]]
   name = "Contact me"
   url = "mailto://isaac.lins07@gmail.com"
