baseURL = "https://isaaclins.com"
languageCode = "en-us"
title = "Isaac Lins"
enableRobotsTXT = true

[module]
  [module.hugoVersion]
    extended = true
    min      = "0.41.0"
[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'images'
target = 'static/images'

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true

  [markup.highlight]
    anchorLineNos      = false
    codeFences         = true
    guessSyntax        = false
    hl_Lines           = ''
    hl_inline          = false
    lineAnchors        = ''
    lineNoStart        = 1
    lineNos            = false
    lineNumbersInTable = true
    noClasses          = true
    noHl               = false
    style              = 'rrt'
    tabWidth           = 4

  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = false

[params]
  # SEO Parameters
  author = "Isaac Lins"
  description = "A blog about tech, programming, and whatever interests me. Deep dives into software, tools, and the digital world."
  tagline = "Tech, Code, and Digital Chaos"
  default_og_image = "/images/pfp.png"
  # twitter_handle = "your_twitter_handle" # Uncomment and add your Twitter handle
  author_url = "https://isaaclins.com"
  logo = "/images/logo.png"
  
  [params.features]
    mermaid = true
  [params.theme_config]
    appearance        = "auto"
    date_format       = "01/02/2006"
    isListGroupByDate = true
    isShowFooter      = true

[taxonomies]
  category = "categories"
  tag = "tags"
  complexity = "complexity"

[outputs]
  section = ["HTML", "RSS", "JSON"]
