[module]
  [module.hugoVersion]
    extended = true
    min      = "0.41.0"
[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'images'
target = 'static/images'

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true

  [markup.highlight]
    anchorLineNos      = false
    codeFences         = true
    guessSyntax        = false
    hl_Lines           = ''
    hl_inline          = false
    lineAnchors        = ''
    lineNoStart        = 1
    lineNos            = false
    lineNumbersInTable = true
    noClasses          = true
    noHl               = false
    style              = 'rrt'
    tabWidth           = 4

  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = false

[params]
  [params.features]
    mermaid = true
  [params.theme_config]
    appearance        = "auto"
    date_format       = "01/02/2006"
    isListGroupByDate = true
    isShowFooter      = true

[taxonomies]
  category = "categories"
  tag = "tags"
  complexity = "complexity"

[outputs]
  section = ["HTML", "RSS", "JSON"]
