baseURL = "https://isaaclins.com"
languageCode = 'en-us'
theme = "coming-soon"

[params]
    title = "'WEBSITE IN DEVELOPMENT' -ISAAC LINS" 
    description = "Please be patient while I rip my veins out my wrist."
    favicon = ""
    message = "COMING SOON!" 
    release = "May 1, 2024" 
    background = "" 
socialIcons = [
{name = "email", url = "isaac.lins07@gmail.com"},         
{name = "github", url = "https://github.com/isaaclins"},    
{name = "linkedin", url = "https://www.linkedin.com/in/isaac-lins-094612247/"},  
]
