name: CI

on:
  push:
    branches: [ "hugo" ]
  pull_request:
    branches: [ "hugo" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build Hugo site
        run: hugo --minify

      - name: Deploy to ./public directory
        run: mv public/* ./public/

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add ./public
          git commit -m "Deploy Hugo site"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: hugo
          
      - name: Hugo-Site
        # You may pin to the exact commit or the version.
        # uses: chabad360/hugo-actions@3a5b10adf0b017f695597e22ebcb79e40fd6cb4e
        uses: chabad360/hugo-actions@v2
        with:
          # The path to build the site to
          buildPath: ./public
          # Arguments to pass to Hugo
          args: --gc --minify --cleanDestinationDir
