name: Lighthouse CI

on:
  push:
    branches:
      - main # Or your default branch
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-get-urls:
    runs-on: ubuntu-latest
    outputs:
      urls: ${{ steps.get_urls.outputs.urls }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest" # Or your specific Hugo version
          extended: true

      - name: Build site
        run: hugo --minify

      - name: List public directory (for debugging)
        run: ls -R public

      - name: Install yq (for parsing XML)
        run: sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq

      - name: Extract URLs from sitemap
        id: get_urls
        run: |
          SITEMAP_PATH="public/sitemap.xml"
          BASE_URL="https://isaaclins.com" # Your website's base URL
          if [ -f "$SITEMAP_PATH" ]; then
            # Extract URLs, ensure they are absolute, and create a JSON array string
            URLS=$(yq -p=xml -o=json '.urlset.url[].loc' "$SITEMAP_PATH" | jq -r --arg BASE_URL "$BASE_URL" 'if type == "array" then .[] else . end | if test("^/") then $BASE_URL + . else . end' | jq -R . | jq -s -c .)
            echo "Found URLs: $URLS"
            echo "urls=$URLS" >> $GITHUB_OUTPUT
          else
            echo "sitemap.xml not found at $SITEMAP_PATH!"
            echo "urls=[]" >> $GITHUB_OUTPUT # Output empty array if sitemap not found
          fi
        shell: bash

  lighthouse-test:
    needs: build-and-get-urls
    # This condition ensures 'urls' output from previous job is a non-empty array when this job runs
    if: fromJson(needs.build-and-get-urls.outputs.urls)[0] != null
    runs-on: ubuntu-latest
    permissions: # Add this to grant write permissions for committing
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare URLs for Lighthouse
        id: prepare_lighthouse_urls
        run: |
          JSON_URL_ARRAY='${{ needs.build-and-get-urls.outputs.urls }}'
          COMMA_SEPARATED_URLS=$(echo "$JSON_URL_ARRAY" | jq -r '. | join(",")')
          echo "Lighthouse URLs: $COMMA_SEPARATED_URLS"
          echo "LIGHTHOUSE_URL_LIST=$COMMA_SEPARATED_URLS" >> $GITHUB_ENV
        shell: bash

      - name: Create Lighthouse reports directory
        run: mkdir -p ./lighthouse-reports

      - name: Run Lighthouse CI for all pages
        id: lighthouse_run
        uses: foo-software/lighthouse-check-action@master
        with:
          urls: ${{ env.LIGHTHOUSE_URL_LIST }}
          outputDirectory: ./lighthouse-reports
          # Optional: Set budget to fail the check if scores are below thresholds
          # budgetPath: .github/lighthouse-budget.json

      - name: Generate Lighthouse Summary Report File
        # This condition makes the step always run, so you see the table even if some Lighthouse audits fail.
        if: always()
        shell: bash
        run: |
          ( # Start subshell to redirect all output to file
          echo "### Lighthouse Score Summary"
          echo "| URL | Accessibility | Best Practices | Performance | SEO |"
          echo "|-----|---------------|----------------|-------------|-----|"
          RESULTS_JSON='${{ steps.lighthouse_run.outputs.lighthouseCheckResults || '{"data":[]}' }}'
          echo "$RESULTS_JSON" | jq -r '.data[]? | select(.url) | ("| " + .url + " | " + (.scores.accessibility // "N/A" | tostring) + " | " + (.scores.bestPractices // "N/A" | tostring) + " | " + (.scores.performance // "N/A" | tostring) + " | " + (.scores.seo // "N/A" | tostring) + " |")'
          ) > README.md # Redirect output to file
          echo "Lighthouse summary report generated: README.md"

      - name: Commit and Push Lighthouse Report
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: Update Lighthouse accessibility report"
          branch: main # Or your default branch
          file_pattern: README.md
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions Bot <actions@github.com>"

      - name: Upload Lighthouse Reports Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-reports # A single artifact for all reports
          path: ./lighthouse-reports
          if-no-files-found: ignore
