name: Push to Hugo branch

on:
  push:
    branches:
      - OFCL

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to Hugo branch
        run: |
          git checkout hugo
          git merge --no-ff --allow-unrelated-histories OFCL -m "Merge changes"
          git push origin hugo
